// SHIFT connector protocol v1 (ADR-0007).
//
// Record batches cross as opaque frames encoded with the engine's binary
// value codec — protobuf never sees individual records.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/connector/v1/connector.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol versions the host can speak, ascending.
	ProtocolVersions []uint32 `protobuf:"varint,1,rep,packed,name=protocol_versions,json=protocolVersions,proto3" json:"protocol_versions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersions() []uint32 {
	if x != nil {
		return x.ProtocolVersions
	}
	return nil
}

type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version the connector selected from the offered set.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Action names this connector exposes.
	SourceActions []string `protobuf:"bytes,4,rep,name=source_actions,json=sourceActions,proto3" json:"source_actions,omitempty"`
	SinkActions   []string `protobuf:"bytes,5,rep,name=sink_actions,json=sinkActions,proto3" json:"sink_actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandshakeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeResponse) GetSourceActions() []string {
	if x != nil {
		return x.SourceActions
	}
	return nil
}

func (x *HandshakeResponse) GetSinkActions() []string {
	if x != nil {
		return x.SinkActions
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type PullRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Connector-specific configuration document (JSON).
	Config        []byte `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{4}
}

func (x *PullRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PullRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

// Frame carries one encoded record batch.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch payload: length-delimited sequence of values in the SHIFT
	// binary value encoding (engine/spill codec).
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Record count in this frame (redundant with payload; lets hosts
	// meter without decoding).
	Records       int64 `protobuf:"varint,2,opt,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

type PushMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PushMessage_Open
	//	*PushMessage_Frame
	Msg           isPushMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{6}
}

func (x *PushMessage) GetMsg() isPushMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PushMessage) GetOpen() *PushOpen {
	if x != nil {
		if x, ok := x.Msg.(*PushMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *PushMessage) GetFrame() *Frame {
	if x != nil {
		if x, ok := x.Msg.(*PushMessage_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isPushMessage_Msg interface {
	isPushMessage_Msg()
}

type PushMessage_Open struct {
	Open *PushOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type PushMessage_Frame struct {
	Frame *Frame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*PushMessage_Open) isPushMessage_Msg() {}

func (*PushMessage_Frame) isPushMessage_Msg() {}

type PushOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOpen) Reset() {
	*x = PushOpen{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOpen) ProtoMessage() {}

func (x *PushOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOpen.ProtoReflect.Descriptor instead.
func (*PushOpen) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{7}
}

func (x *PushOpen) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PushOpen) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type PushSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       int64                  `protobuf:"varint,1,opt,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSummary) Reset() {
	*x = PushSummary{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSummary) ProtoMessage() {}

func (x *PushSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSummary.ProtoReflect.Descriptor instead.
func (*PushSummary) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{8}
}

func (x *PushSummary) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{9}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{10}
}

var File_proto_connector_v1_connector_proto protoreflect.FileDescriptor

const file_proto_connector_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\"proto/connector/v1/connector.proto\x12\x12shift.connector.v1\"?\n" +
	"\x10HandshakeRequest\x12+\n" +
	"\x11protocol_versions\x18\x01 \x03(\rR\x10protocolVersions\"\xb6\x01\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0esource_actions\x18\x04 \x03(\tR\rsourceActions\x12!\n" +
	"\fsink_actions\x18\x05 \x03(\tR\vsinkActions\"\x0f\n" +
	"\rHealthRequest\"8\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"=\n" +
	"\vPullRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\";\n" +
	"\x05Frame\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x18\n" +
	"\arecords\x18\x02 \x01(\x03R\arecords\"{\n" +
	"\vPushMessage\x122\n" +
	"\x04open\x18\x01 \x01(\v2\x1c.shift.connector.v1.PushOpenH\x00R\x04open\x121\n" +
	"\x05frame\x18\x02 \x01(\v2\x19.shift.connector.v1.FrameH\x00R\x05frameB\x05\n" +
	"\x03msg\":\n" +
	"\bPushOpen\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\"'\n" +
	"\vPushSummary\x12\x18\n" +
	"\arecords\x18\x01 \x01(\x03R\arecords\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\x9f\x03\n" +
	"\tConnector\x12X\n" +
	"\tHandshake\x12$.shift.connector.v1.HandshakeRequest\x1a%.shift.connector.v1.HandshakeResponse\x12O\n" +
	"\x06Health\x12!.shift.connector.v1.HealthRequest\x1a\".shift.connector.v1.HealthResponse\x12D\n" +
	"\x04Pull\x12\x1f.shift.connector.v1.PullRequest\x1a\x19.shift.connector.v1.Frame0\x01\x12J\n" +
	"\x04Push\x12\x1f.shift.connector.v1.PushMessage\x1a\x1f.shift.connector.v1.PushSummary(\x01\x12U\n" +
	"\bShutdown\x12#.shift.connector.v1.ShutdownRequest\x1a$.shift.connector.v1.ShutdownResponseB+Z)github.com/aaron-au/shift/sdk/connectorpbb\x06proto3"

var (
	file_proto_connector_v1_connector_proto_rawDescOnce sync.Once
	file_proto_connector_v1_connector_proto_rawDescData []byte
)

func file_proto_connector_v1_connector_proto_rawDescGZIP() []byte {
	file_proto_connector_v1_connector_proto_rawDescOnce.Do(func() {
		file_proto_connector_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connector_v1_connector_proto_rawDesc), len(file_proto_connector_v1_connector_proto_rawDesc)))
	})
	return file_proto_connector_v1_connector_proto_rawDescData
}

var file_proto_connector_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_connector_v1_connector_proto_goTypes = []any{
	(*HandshakeRequest)(nil),  // 0: shift.connector.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 1: shift.connector.v1.HandshakeResponse
	(*HealthRequest)(nil),     // 2: shift.connector.v1.HealthRequest
	(*HealthResponse)(nil),    // 3: shift.connector.v1.HealthResponse
	(*PullRequest)(nil),       // 4: shift.connector.v1.PullRequest
	(*Frame)(nil),             // 5: shift.connector.v1.Frame
	(*PushMessage)(nil),       // 6: shift.connector.v1.PushMessage
	(*PushOpen)(nil),          // 7: shift.connector.v1.PushOpen
	(*PushSummary)(nil),       // 8: shift.connector.v1.PushSummary
	(*ShutdownRequest)(nil),   // 9: shift.connector.v1.ShutdownRequest
	(*ShutdownResponse)(nil),  // 10: shift.connector.v1.ShutdownResponse
}
var file_proto_connector_v1_connector_proto_depIdxs = []int32{
	7,  // 0: shift.connector.v1.PushMessage.open:type_name -> shift.connector.v1.PushOpen
	5,  // 1: shift.connector.v1.PushMessage.frame:type_name -> shift.connector.v1.Frame
	0,  // 2: shift.connector.v1.Connector.Handshake:input_type -> shift.connector.v1.HandshakeRequest
	2,  // 3: shift.connector.v1.Connector.Health:input_type -> shift.connector.v1.HealthRequest
	4,  // 4: shift.connector.v1.Connector.Pull:input_type -> shift.connector.v1.PullRequest
	6,  // 5: shift.connector.v1.Connector.Push:input_type -> shift.connector.v1.PushMessage
	9,  // 6: shift.connector.v1.Connector.Shutdown:input_type -> shift.connector.v1.ShutdownRequest
	1,  // 7: shift.connector.v1.Connector.Handshake:output_type -> shift.connector.v1.HandshakeResponse
	3,  // 8: shift.connector.v1.Connector.Health:output_type -> shift.connector.v1.HealthResponse
	5,  // 9: shift.connector.v1.Connector.Pull:output_type -> shift.connector.v1.Frame
	8,  // 10: shift.connector.v1.Connector.Push:output_type -> shift.connector.v1.PushSummary
	10, // 11: shift.connector.v1.Connector.Shutdown:output_type -> shift.connector.v1.ShutdownResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_connector_v1_connector_proto_init() }
func file_proto_connector_v1_connector_proto_init() {
	if File_proto_connector_v1_connector_proto != nil {
		return
	}
	file_proto_connector_v1_connector_proto_msgTypes[6].OneofWrappers = []any{
		(*PushMessage_Open)(nil),
		(*PushMessage_Frame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connector_v1_connector_proto_rawDesc), len(file_proto_connector_v1_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connector_v1_connector_proto_goTypes,
		DependencyIndexes: file_proto_connector_v1_connector_proto_depIdxs,
		MessageInfos:      file_proto_connector_v1_connector_proto_msgTypes,
	}.Build()
	File_proto_connector_v1_connector_proto = out.File
	file_proto_connector_v1_connector_proto_goTypes = nil
	file_proto_connector_v1_connector_proto_depIdxs = nil
}
