#!/usr/bin/env python3
"""Render docs/bench-M7/results.md from the shift-bench JSON in a results dir.

Usage: bench_report.py <results-dir> <bytes-label> <runs>

Reads every <scenario>.json (a benchReport: scenario, runs[], summary{}) and
emits a single markdown table plus per-scenario operator breakdowns. Pure
stdlib so it runs anywhere CI does.
"""
import json
import pathlib
import sys


def mib(n):
    return f"{n / (1 << 20):.1f} MiB"


def main():
    results_dir = pathlib.Path(sys.argv[1])
    bytes_label = sys.argv[2] if len(sys.argv) > 2 else "?"
    runs = sys.argv[3] if len(sys.argv) > 3 else "?"

    reports = []
    for path in sorted(results_dir.glob("*.json")):
        with path.open() as fh:
            reports.append(json.load(fh))

    out = []
    out.append("# shift-bench results")
    out.append("")
    out.append(
        f"Input **{bytes_label}** per scenario, **{runs}** run(s) each "
        "(median reported, one untimed warmup). Peak RSS is the worst across "
        "runs — the number the M1 RSS gate checks (ADR-0003)."
    )
    out.append("")
    out.append(
        "| Scenario | Throughput | Median wall | Peak RSS | Records out "
        "| B/rec | allocs/rec | Spill |"
    )
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    for rep in reports:
        s = rep["summary"]
        first = rep["runs"][0]
        out.append(
            f"| {rep['scenario']} "
            f"| {s['median_mib_per_sec']:.1f} MiB/s "
            f"| {s['median_wall_nanos'] / 1e9:.2f}s "
            f"| {mib(s['worst_peak_rss_bytes'])} "
            f"| {first['records_out']:,} "
            f"| {first['bytes_per_record']} "
            f"| {first['allocs_per_record']:.2f} "
            f"| {mib(first['spill_bytes'])} |"
        )
    out.append("")
    out.append(
        "_Generated by `make bench-report` (`scripts/bench.sh`). Regenerate "
        "after engine changes; commit alongside the diff._"
    )
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
